const ADD_USER = 'ADD_USER';
const DELETE_USER = 'DELETE_USER';
const EDIT_USER = 'EDIT_USER';
const ALL_USERS = 'ALL_USERS';
const ONE_USER = 'ONE_USER';

export {
  ADD_USER,
  DELETE_USER,
  EDIT_USER,
  ALL_USERS,
  ONE_USER
};
